// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2lA34y4nJtjif885PYQSSzizB8oFEv-o',
    appId: '1:1086158122863:web:3638f0b3b774cd0dd6429a',
    messagingSenderId: '1086158122863',
    projectId: 'sobhamart-customer',
    authDomain: 'sobhamart-customer.firebaseapp.com',
    storageBucket: 'sobhamart-customer.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn2Lv7SBfDr12Q1GlfW9aTTuxggGXHM7Q',
    appId: '1:1086158122863:android:1c1914bc1ed6f112d6429a',
    messagingSenderId: '1086158122863',
    projectId: 'sobhamart-customer',
    storageBucket: 'sobhamart-customer.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUSwDBBUiqnUsH1FgcdBOQIyyglrnbGM0',
    appId: '1:1086158122863:ios:c404cb006a6148b2d6429a',
    messagingSenderId: '1086158122863',
    projectId: 'sobhamart-customer',
    storageBucket: 'sobhamart-customer.firebasestorage.app',
    iosBundleId: 'com.example.smDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUSwDBBUiqnUsH1FgcdBOQIyyglrnbGM0',
    appId: '1:1086158122863:ios:c404cb006a6148b2d6429a',
    messagingSenderId: '1086158122863',
    projectId: 'sobhamart-customer',
    storageBucket: 'sobhamart-customer.firebasestorage.app',
    iosBundleId: 'com.example.smDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2lA34y4nJtjif885PYQSSzizB8oFEv-o',
    appId: '1:1086158122863:web:03567b08bf97c492d6429a',
    messagingSenderId: '1086158122863',
    projectId: 'sobhamart-customer',
    authDomain: 'sobhamart-customer.firebaseapp.com',
    storageBucket: 'sobhamart-customer.firebasestorage.app',
  );
}
